services:

  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: juice-waf
    ports:
      - "8081:8080"
    environment:
      - BACKEND=http://juice-shop:3000
      - PORT=8080
      - MODSEC_RULE_ENGINE=On
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
    volumes:
      - ./nginx_waf.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./modsecurity_juiceshop.conf:/etc/modsecurity.d/custom_juiceshop.conf:ro
      - waf_logs:/var/log/nginx
    networks:
      - juicenet
    restart: unless-stopped


  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: filebeat
    user: root
    volumes:
      - waf_logs:/var/log/nginx:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - juicenet
    restart: unless-stopped


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - juicenet
    restart: unless-stopped


  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - juicenet
    restart: unless-stopped


volumes:
  waf_logs:
  esdata:

networks:
  juicenet:
    external: true