# Rate limiting zones
limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;
limit_req_zone $binary_remote_addr zone=general:10m rate=60r/m;

server {
    listen 8080;

    # Headers sécurité
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; object-src 'none';" always;

    # Bloquer null byte dans les URIs FTP (%2500, %00, %25)
    location ~* ^/ftp/ {
        if ($request_uri ~* "%25|%00|\x00") {
            return 400;
        }
        proxy_pass http://juice-shop:3000;
    }

    # Rate limiting sur login
    location = /rest/user/login {
        limit_req zone=login burst=3 nodelay;
        limit_req_status 429;
        proxy_pass http://juice-shop:3000;
    }

    # Rate limiting général
    location / {
        limit_req zone=general burst=20 nodelay;
        proxy_pass http://juice-shop:3000;
    }
}
