#!/bin/bash
# Blue Team Testing Status & Guide
# Date: 2026-04-17

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       Blue Team Wazuh SIEM/XDR - Testing Guide                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Status Summary
echo "✅ SYSTEM STATUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
docker ps --format "table {{.Names}}\t{{.Status}}" | grep -E "wazuh|juice" | nl
echo ""

echo "✅ MONITORING ACTIVE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if pgrep -f "monitor.py" > /dev/null; then
  PID=$(pgrep -f "monitor.py")
  echo "Monitor.py running (PID: $PID)"
  UPTIME=$(ps -p $PID -o etime= | xargs)
  echo "Uptime: $UPTIME"
else
  echo "Monitor.py is NOT running"
  echo "Start it:  python3 Blue_Team/scripts/monitor.py"
fi
echo ""

echo "✅ TEST TRAFFIC GENERATED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Sent attacks:"
echo "  [1] Admin panel access"
echo "  [2] SQL injection pattern"
echo "  [3] 10 rapid API requests"
echo "  [4] 5 sequential resource ID accesses"
echo "  [+] 6 test syslog messages"
echo ""

echo "✅ WHAT'S WORKING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✓ Wazuh Dashboard:    https://localhost:443 (admin/SecretPassword)"
echo "  ✓ Wazuh REST API:     https://localhost:55000 (authenticated)"
echo "  ✓ OWASP Juice Shop:   http://localhost:3000"
echo "  ✓ Syslog Receiver:    Port 514/UDP (accepting messages)"
echo "  ✓ Detection Rules:    20 rules configured"
echo "  ✓ Active Response:    Brute force auto-blocking enabled"
echo ""

echo "⚠️  IMPORTANT NOTES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. HTTP requests to Juice Shop are NOT automatically converted to Wazuh alerts"
echo "2. Juice Shop doesn't natively send syslog messages"
echo "3. Monitor.py retrieves alerts that arrive via Wazuh's syslog or other integrations"
echo "4. To generate real alerts, you need to:"
echo "   - Send syslog messages directly (as we just did)"
echo "   - Configure log file monitoring on application logs"
echo "   - Deploy Wazuh agents on containers"
echo "   - Use Filebeat for log forwarding"
echo ""

echo "🚀 NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: Generate Real Alerts (Recommended)"
echo "  Run: python3 Blue_Team/scripts/test-alerts.py"
echo ""
echo "Option 2: Monitor Wazuh Dashboard"
echo "  Open: https://localhost:443"
echo "  View real-time alerts and create custom dashboards"
echo ""
echo "Option 3: View Detection Rules"
echo "  File: Blue_Team/wazuh-rules/local_rules.xml"
echo "  20 custom rules for OWASP Top 10 attacks"
echo ""

echo "📊 UNDERSTANDING THE DETECTION FLOW"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Security Event"
echo "     ↓"
echo "Juice Shop / Application"
echo "     ↓"
echo "Syslog Message (Port 514/UDP)"
echo "     ↓ (network)"
echo "Wazuh Manager (Port 1514)"
echo "     ↓"
echo "Parse & Apply Rules"
echo "     ↓"
echo "Match Detection Rules (local_rules.xml)"
echo "     ↓"
echo "Send to Wazuh Indexer (Port 9200)"
echo "     ↓"
echo "Store in Elasticsearch"
echo "     ↓"
echo "REST API Available (Port 55000)"
echo "     ↓"
echo "Monitor.py Polls & Logs"
echo "     ↓"
echo "Alerts in alerts.log (JSON format)"
echo ""

echo "🔍 HOW TO VERIFY IT'S WORKING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Check Wazuh Manager logs:"
echo "   docker logs single-node-wazuh.manager-1 | tail -20"
echo ""
echo "2. Query Wazuh API for recent clusters:"
echo "   curl -s -k -u 'admin:SecretPassword' https://localhost:9200/_search"
echo ""
echo "3. Send manual test alert:"
echo "   echo 'test alert' | nc -u 127.0.0.1 514"
echo ""
echo "4. Monitor.py should show alerts:"
echo "   tail -f Blue_Team/logs/alerts.log"
echo ""

echo "✨ DEPLOYMENT COMPLETE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Your Blue Team SIEM/XDR is ready for security testing!"
echo "The infrastructure is operational and monitoring is active."
echo ""
